import "../globals.css";
import SessionHandler from "@/components/SessionHandler";
import Navbar_NoFlat from "@/components/Navbar_NoFlat";

export const metadata = {
  title: "Finova",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionHandler>
      <main className="max-w-screen h-screen w-screen bg-background">
        <div className="w-screen h-20">
          <Navbar_NoFlat />
        </div>

        <div className="h-[calc(100vh-5rem)] w-screen">{children}</div>
      </main>
    </SessionHandler>
  );
}
