# Generated by Django 6.0.2 on 2026-02-23 12:34

import flats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="join_code",
            field=models.CharField(
                default=flats.models.generate_join_code, max_length=4
            ),
        ),
    ]
