# Generated by Django 6.0.2 on 2026-02-23 13:47

import django.db.models.deletion
import flats.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0002_flat_join_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="join_code",
            field=models.CharField(
                default=flats.models.generate_join_code, max_length=4, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
