# Generated by Django 6.0.2 on 2026-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0003_alter_flat_join_code_alter_membership_resident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="max_residents",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
