import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SessionHandler from "@/components/SessionHandler";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Finova",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionHandler>
      <main className="max-w-screen h-screen w-screen bg-background">
        <div className="w-screen h-20">
          <Navbar />
        </div>

        <div className="h-[calc(100vh-5rem)] w-screen">{children}</div>
      </main>
    </SessionHandler>
  );
}
