import "../globals.css";
import SessionHandler from "@/components/SessionHandler";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Finova",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionHandler>
      <main className="h-screen  w-screen bg-background overflow-y-scroll">
        <div className="w-screen h-20">
          <Navbar />
        </div>

        <div className="h-[calc(100vh-5rem)] w-screen">{children}</div>
      </main>
    </SessionHandler>
  );
}
