import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Finova",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={` max-w-screen bg-black`}>
      <div className="w-screen h-screen overflow-x-hidden overflow-y-scroll">
        {children}
      </div>
    </div>
  );
}
