# Generated by Django 6.0.2 on 2026-03-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="new_budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.CharField(
                choices=[("N", "Normal"), ("B", "Budget")], default="N", max_length=2
            ),
        ),
    ]
